Repository orange-cloudavenue/cloudavenue-cli, pull requests merged in 2024-01, with the labels that each got.

#46 chore: move package print to external library
  cmd/get.go
  go.mod
  go.sum
  pkg/print/print.go
  pkg/templates/json/json.go
Labels: enhancement

#48 chore: Add animation
  .changelog/43.txt
  .changelog/44.txt
  .changelog/47.txt
  cmd/create.go
  cmd/del.go
  cmd/get.go
  cmd/root.go
  go.mod
  go.sum
Labels: enhancement

#54 chore: Fix version command, binary name for darwin and add template PR
  .changelog/51.txt
  .github/PULL_REQUEST_TEMPLATE.md
  .goreleaser.yaml
  cmd/root.go
Labels: bug

#60 feat(doc): improve documentation
  .changelog/59.txt
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check_gen-doc.yml
  .github/workflows/deploy_documentation.yml
  .vscode/extensions.json
  .vscode/settings.json
  GNUmakefile
  README.md
  cmd/root.go
  docs/command/cav.md
  docs/command/cav_completion.md
  docs/command/cav_completion_bash.md
  docs/command/cav_completion_fish.md
  docs/command/cav_completion_powershell.md
  docs/command/cav_completion_zsh.md
  docs/command/cav_create.md
  docs/command/cav_create_edgegateway.md
  docs/command/cav_create_publicip.md
  docs/command/cav_create_s3.md
  docs/command/cav_create_vdc.md
  docs/command/cav_delete.md
  docs/command/cav_delete_edgegateway.md
  docs/command/cav_delete_publicip.md
  docs/command/cav_delete_s3.md
  docs/command/cav_delete_vdc.md
  docs/command/cav_gen-doc.md
  docs/command/cav_get.md
  docs/command/cav_get_edgegateway.md
  docs/command/cav_get_publicip.md
  docs/command/cav_get_s3.md
  docs/command/cav_get_t0.md
  docs/command/cav_get_vdc.md
  docs/command/cav_version.md
  docs/getting-started/configuration.md
  docs/getting-started/installation.md
  docs/index.md
  go.mod
  go.sum
  go.work
  go.work.sum
  mkdocs.yml
Labels: documentation, enhancement

#62 chore: move gen-doc to go:generate
  .changelog/57.txt
  .changelog/59.txt
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy_documentation.yml
  .gitignore
  GNUmakefile
  cmd/create.go
  cmd/del.go
  cmd/get.go
  cmd/root.go
  docs/command/cav.md
  docs/command/cav_completion.md
  docs/command/cav_completion_bash.md
  docs/command/cav_completion_fish.md
  docs/command/cav_completion_powershell.md
  docs/command/cav_completion_zsh.md
  docs/command/cav_create.md
  docs/command/cav_create_edgegateway.md
  docs/command/cav_create_publicip.md
  docs/command/cav_create_s3.md
  docs/command/cav_create_vdc.md
  docs/command/cav_delete.md
  docs/command/cav_delete_edgegateway.md
  docs/command/cav_delete_publicip.md
  docs/command/cav_delete_s3.md
  docs/command/cav_delete_vdc.md
  docs/command/cav_gen-doc.md
  docs/command/cav_get.md
  docs/command/cav_get_edgegateway.md
  docs/command/cav_get_publicip.md
  docs/command/cav_get_s3.md
  docs/command/cav_get_t0.md
  docs/command/cav_get_vdc.md
  docs/command/cav_version.md
  docs/getting-started/configuration.md
  docs/index.md
  go.work
  go.work.sum
  main.go
  mkdocs.yml
  scripts/install.sh
  tools/tools.go
Labels: documentation, enhancement
